### ISSUE TITLE
invalid json response body

### ISSUE THREAD

**Issue by khurrambilal01** [del-systems/check-if-version-bumped#4]
Hi,
I've trying to use the action as set in example, fetching package.json returns failure as stated below.
Further it would be good if we can set the path for package.json file as some projects do have separate for frontend and backend.

Error:

Comparing ee7d4fc666a7f888df78e229fe0dc88012bd7be4 to 98017874194498c180b3c2b91195b80234dac410
Error: FetchError: invalid json response body at https://raw.githubusercontent.com/ORG/repository/98017874194498c180b3c2b91195b80234dac410/package.json reason: Unexpected token : in JSON at position 3

**Comment by GRiMe2D** [comment]
Hi @khurrambilal01!

I'm glad that you're interested in using my code! I can make it to accept optional path for package.json, but do you really want it?

Because it will require that package.json to updated every push to a protected branch

**Comment by vandijkstef** [comment]
I want it https://github.com/del-systems/check-if-version-bumped/pull/5

**Comment by GRiMe2D** [comment]
Updated `v1` tag. It should use the latest version. Change your GitHub action scripts accordingly: add `path` input to the desired package.json file. Do not start with `/`
